### Задание 1

In [6]:
import numpy as np

In [38]:
a_1 = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a_1

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [39]:
a = a_1.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [20]:
mean_a = a_t.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [23]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [35]:
a_1 = a_centered[:, 0].copy()
a_1

array([-1.,  0.,  1.,  1., -1.])

In [36]:
a_2 = a_centered[:, 1].copy()
a_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [37]:
a_centered_sp = a_1 @ a_2
a_centered_sp

8.0

In [42]:
N = a.shape[0]
N

5

In [43]:
a_centered_sp / (N - 1)

2.0

### Задание 4

In [45]:
a_t = a.T
cov = np.cov(a_t)
cov[0, 1]

2.0